"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class controlCommands(object):
    __slots__ = ["channels", "frame"]

    __typenames__ = ["double", "int64_t"]

    __dimensions__ = [[6], None]

    def __init__(self):
        self.channels = [ 0.0 for dim0 in range(6) ]
        self.frame = 0

    def encode(self):
        buf = BytesIO()
        buf.write(controlCommands._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>6d', *self.channels[:6]))
        buf.write(struct.pack(">q", self.frame))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != controlCommands._get_packed_fingerprint():
            raise ValueError("Decode error")
        return controlCommands._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = controlCommands()
        self.channels = struct.unpack('>6d', buf.read(48))
        self.frame = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if controlCommands in parents: return 0
        tmphash = (0xcc33713b8fe62cb4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if controlCommands._packed_fingerprint is None:
            controlCommands._packed_fingerprint = struct.pack(">Q", controlCommands._get_hash_recursive([]))
        return controlCommands._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

