"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class vicon_state(object):
    __slots__ = ["position", "angles", "velocity", "anglular_rates"]

    __typenames__ = ["double", "double", "double", "double"]

    __dimensions__ = [[3], [3], [3], [3]]

    def __init__(self):
        self.position = [ 0.0 for dim0 in range(3) ]
        self.angles = [ 0.0 for dim0 in range(3) ]
        self.velocity = [ 0.0 for dim0 in range(3) ]
        self.anglular_rates = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(vicon_state._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3d', *self.position[:3]))
        buf.write(struct.pack('>3d', *self.angles[:3]))
        buf.write(struct.pack('>3d', *self.velocity[:3]))
        buf.write(struct.pack('>3d', *self.anglular_rates[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vicon_state._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vicon_state._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = vicon_state()
        self.position = struct.unpack('>3d', buf.read(24))
        self.angles = struct.unpack('>3d', buf.read(24))
        self.velocity = struct.unpack('>3d', buf.read(24))
        self.anglular_rates = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if vicon_state in parents: return 0
        tmphash = (0x7b68f6ad8f4b178b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if vicon_state._packed_fingerprint is None:
            vicon_state._packed_fingerprint = struct.pack(">Q", vicon_state._get_hash_recursive([]))
        return vicon_state._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

